/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/signIn'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedOperadoresIndexRouteImport } from './routes/_protected/operadores/index'
import { Route as ProtectedListarEmprestimosIndexRouteImport } from './routes/_protected/listar-emprestimos/index'
import { Route as ProtectedEmprestimosIndexRouteImport } from './routes/_protected/emprestimos/index'
import { Route as ProtectedOperadoresCadastroRouteImport } from './routes/_protected/operadores/cadastro'

const SignInRoute = SignInRouteImport.update({
  id: '/signIn',
  path: '/signIn',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedOperadoresIndexRoute =
  ProtectedOperadoresIndexRouteImport.update({
    id: '/operadores/',
    path: '/operadores/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedListarEmprestimosIndexRoute =
  ProtectedListarEmprestimosIndexRouteImport.update({
    id: '/listar-emprestimos/',
    path: '/listar-emprestimos/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedEmprestimosIndexRoute =
  ProtectedEmprestimosIndexRouteImport.update({
    id: '/emprestimos/',
    path: '/emprestimos/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedOperadoresCadastroRoute =
  ProtectedOperadoresCadastroRouteImport.update({
    id: '/operadores/cadastro',
    path: '/operadores/cadastro',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signIn': typeof SignInRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/operadores/cadastro': typeof ProtectedOperadoresCadastroRoute
  '/emprestimos': typeof ProtectedEmprestimosIndexRoute
  '/listar-emprestimos': typeof ProtectedListarEmprestimosIndexRoute
  '/operadores': typeof ProtectedOperadoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signIn': typeof SignInRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/operadores/cadastro': typeof ProtectedOperadoresCadastroRoute
  '/emprestimos': typeof ProtectedEmprestimosIndexRoute
  '/listar-emprestimos': typeof ProtectedListarEmprestimosIndexRoute
  '/operadores': typeof ProtectedOperadoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/signIn': typeof SignInRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/operadores/cadastro': typeof ProtectedOperadoresCadastroRoute
  '/_protected/emprestimos/': typeof ProtectedEmprestimosIndexRoute
  '/_protected/listar-emprestimos/': typeof ProtectedListarEmprestimosIndexRoute
  '/_protected/operadores/': typeof ProtectedOperadoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signIn'
    | '/dashboard'
    | '/operadores/cadastro'
    | '/emprestimos'
    | '/listar-emprestimos'
    | '/operadores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signIn'
    | '/dashboard'
    | '/operadores/cadastro'
    | '/emprestimos'
    | '/listar-emprestimos'
    | '/operadores'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/signIn'
    | '/_protected/dashboard'
    | '/_protected/operadores/cadastro'
    | '/_protected/emprestimos/'
    | '/_protected/listar-emprestimos/'
    | '/_protected/operadores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signIn': {
      id: '/signIn'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/operadores/': {
      id: '/_protected/operadores/'
      path: '/operadores'
      fullPath: '/operadores'
      preLoaderRoute: typeof ProtectedOperadoresIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/listar-emprestimos/': {
      id: '/_protected/listar-emprestimos/'
      path: '/listar-emprestimos'
      fullPath: '/listar-emprestimos'
      preLoaderRoute: typeof ProtectedListarEmprestimosIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/emprestimos/': {
      id: '/_protected/emprestimos/'
      path: '/emprestimos'
      fullPath: '/emprestimos'
      preLoaderRoute: typeof ProtectedEmprestimosIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/operadores/cadastro': {
      id: '/_protected/operadores/cadastro'
      path: '/operadores/cadastro'
      fullPath: '/operadores/cadastro'
      preLoaderRoute: typeof ProtectedOperadoresCadastroRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedOperadoresCadastroRoute: typeof ProtectedOperadoresCadastroRoute
  ProtectedEmprestimosIndexRoute: typeof ProtectedEmprestimosIndexRoute
  ProtectedListarEmprestimosIndexRoute: typeof ProtectedListarEmprestimosIndexRoute
  ProtectedOperadoresIndexRoute: typeof ProtectedOperadoresIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedOperadoresCadastroRoute: ProtectedOperadoresCadastroRoute,
  ProtectedEmprestimosIndexRoute: ProtectedEmprestimosIndexRoute,
  ProtectedListarEmprestimosIndexRoute: ProtectedListarEmprestimosIndexRoute,
  ProtectedOperadoresIndexRoute: ProtectedOperadoresIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
