/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/signIn'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedOperadoresRouteRouteImport } from './routes/_protected/operadores/route'
import { Route as ProtectedOperadoresIndexRouteImport } from './routes/_protected/operadores/index'
import { Route as ProtectedListarEmprestimosIndexRouteImport } from './routes/_protected/listar-emprestimos/index'
import { Route as ProtectedEmprestimosIndexRouteImport } from './routes/_protected/emprestimos/index'
import { Route as ProtectedOperadoresCadastroRouteImport } from './routes/_protected/operadores/cadastro'
import { Route as ProtectedListarEmprestimosIdRouteImport } from './routes/_protected/listar-emprestimos/$id'
import { Route as ProtectedEmprestimosEmprestimoAdministrativoIndexRouteImport } from './routes/_protected/emprestimos/emprestimo-administrativo/index'

const SignInRoute = SignInRouteImport.update({
  id: '/signIn',
  path: '/signIn',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedOperadoresRouteRoute =
  ProtectedOperadoresRouteRouteImport.update({
    id: '/operadores',
    path: '/operadores',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedOperadoresIndexRoute =
  ProtectedOperadoresIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOperadoresRouteRoute,
  } as any)
const ProtectedListarEmprestimosIndexRoute =
  ProtectedListarEmprestimosIndexRouteImport.update({
    id: '/listar-emprestimos/',
    path: '/listar-emprestimos/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedEmprestimosIndexRoute =
  ProtectedEmprestimosIndexRouteImport.update({
    id: '/emprestimos/',
    path: '/emprestimos/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedOperadoresCadastroRoute =
  ProtectedOperadoresCadastroRouteImport.update({
    id: '/cadastro',
    path: '/cadastro',
    getParentRoute: () => ProtectedOperadoresRouteRoute,
  } as any)
const ProtectedListarEmprestimosIdRoute =
  ProtectedListarEmprestimosIdRouteImport.update({
    id: '/listar-emprestimos/$id',
    path: '/listar-emprestimos/$id',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedEmprestimosEmprestimoAdministrativoIndexRoute =
  ProtectedEmprestimosEmprestimoAdministrativoIndexRouteImport.update({
    id: '/emprestimos/emprestimo-administrativo/',
    path: '/emprestimos/emprestimo-administrativo/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signIn': typeof SignInRoute
  '/operadores': typeof ProtectedOperadoresRouteRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRoute
  '/listar-emprestimos/$id': typeof ProtectedListarEmprestimosIdRoute
  '/operadores/cadastro': typeof ProtectedOperadoresCadastroRoute
  '/emprestimos': typeof ProtectedEmprestimosIndexRoute
  '/listar-emprestimos': typeof ProtectedListarEmprestimosIndexRoute
  '/operadores/': typeof ProtectedOperadoresIndexRoute
  '/emprestimos/emprestimo-administrativo': typeof ProtectedEmprestimosEmprestimoAdministrativoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signIn': typeof SignInRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/listar-emprestimos/$id': typeof ProtectedListarEmprestimosIdRoute
  '/operadores/cadastro': typeof ProtectedOperadoresCadastroRoute
  '/emprestimos': typeof ProtectedEmprestimosIndexRoute
  '/listar-emprestimos': typeof ProtectedListarEmprestimosIndexRoute
  '/operadores': typeof ProtectedOperadoresIndexRoute
  '/emprestimos/emprestimo-administrativo': typeof ProtectedEmprestimosEmprestimoAdministrativoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/signIn': typeof SignInRoute
  '/_protected/operadores': typeof ProtectedOperadoresRouteRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/listar-emprestimos/$id': typeof ProtectedListarEmprestimosIdRoute
  '/_protected/operadores/cadastro': typeof ProtectedOperadoresCadastroRoute
  '/_protected/emprestimos/': typeof ProtectedEmprestimosIndexRoute
  '/_protected/listar-emprestimos/': typeof ProtectedListarEmprestimosIndexRoute
  '/_protected/operadores/': typeof ProtectedOperadoresIndexRoute
  '/_protected/emprestimos/emprestimo-administrativo/': typeof ProtectedEmprestimosEmprestimoAdministrativoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signIn'
    | '/operadores'
    | '/dashboard'
    | '/listar-emprestimos/$id'
    | '/operadores/cadastro'
    | '/emprestimos'
    | '/listar-emprestimos'
    | '/operadores/'
    | '/emprestimos/emprestimo-administrativo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signIn'
    | '/dashboard'
    | '/listar-emprestimos/$id'
    | '/operadores/cadastro'
    | '/emprestimos'
    | '/listar-emprestimos'
    | '/operadores'
    | '/emprestimos/emprestimo-administrativo'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/signIn'
    | '/_protected/operadores'
    | '/_protected/dashboard'
    | '/_protected/listar-emprestimos/$id'
    | '/_protected/operadores/cadastro'
    | '/_protected/emprestimos/'
    | '/_protected/listar-emprestimos/'
    | '/_protected/operadores/'
    | '/_protected/emprestimos/emprestimo-administrativo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signIn': {
      id: '/signIn'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/operadores': {
      id: '/_protected/operadores'
      path: '/operadores'
      fullPath: '/operadores'
      preLoaderRoute: typeof ProtectedOperadoresRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/operadores/': {
      id: '/_protected/operadores/'
      path: '/'
      fullPath: '/operadores/'
      preLoaderRoute: typeof ProtectedOperadoresIndexRouteImport
      parentRoute: typeof ProtectedOperadoresRouteRoute
    }
    '/_protected/listar-emprestimos/': {
      id: '/_protected/listar-emprestimos/'
      path: '/listar-emprestimos'
      fullPath: '/listar-emprestimos'
      preLoaderRoute: typeof ProtectedListarEmprestimosIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/emprestimos/': {
      id: '/_protected/emprestimos/'
      path: '/emprestimos'
      fullPath: '/emprestimos'
      preLoaderRoute: typeof ProtectedEmprestimosIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/operadores/cadastro': {
      id: '/_protected/operadores/cadastro'
      path: '/cadastro'
      fullPath: '/operadores/cadastro'
      preLoaderRoute: typeof ProtectedOperadoresCadastroRouteImport
      parentRoute: typeof ProtectedOperadoresRouteRoute
    }
    '/_protected/listar-emprestimos/$id': {
      id: '/_protected/listar-emprestimos/$id'
      path: '/listar-emprestimos/$id'
      fullPath: '/listar-emprestimos/$id'
      preLoaderRoute: typeof ProtectedListarEmprestimosIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/emprestimos/emprestimo-administrativo/': {
      id: '/_protected/emprestimos/emprestimo-administrativo/'
      path: '/emprestimos/emprestimo-administrativo'
      fullPath: '/emprestimos/emprestimo-administrativo'
      preLoaderRoute: typeof ProtectedEmprestimosEmprestimoAdministrativoIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedOperadoresRouteRouteChildren {
  ProtectedOperadoresCadastroRoute: typeof ProtectedOperadoresCadastroRoute
  ProtectedOperadoresIndexRoute: typeof ProtectedOperadoresIndexRoute
}

const ProtectedOperadoresRouteRouteChildren: ProtectedOperadoresRouteRouteChildren =
  {
    ProtectedOperadoresCadastroRoute: ProtectedOperadoresCadastroRoute,
    ProtectedOperadoresIndexRoute: ProtectedOperadoresIndexRoute,
  }

const ProtectedOperadoresRouteRouteWithChildren =
  ProtectedOperadoresRouteRoute._addFileChildren(
    ProtectedOperadoresRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedOperadoresRouteRoute: typeof ProtectedOperadoresRouteRouteWithChildren
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedListarEmprestimosIdRoute: typeof ProtectedListarEmprestimosIdRoute
  ProtectedEmprestimosIndexRoute: typeof ProtectedEmprestimosIndexRoute
  ProtectedListarEmprestimosIndexRoute: typeof ProtectedListarEmprestimosIndexRoute
  ProtectedEmprestimosEmprestimoAdministrativoIndexRoute: typeof ProtectedEmprestimosEmprestimoAdministrativoIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedOperadoresRouteRoute: ProtectedOperadoresRouteRouteWithChildren,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedListarEmprestimosIdRoute: ProtectedListarEmprestimosIdRoute,
  ProtectedEmprestimosIndexRoute: ProtectedEmprestimosIndexRoute,
  ProtectedListarEmprestimosIndexRoute: ProtectedListarEmprestimosIndexRoute,
  ProtectedEmprestimosEmprestimoAdministrativoIndexRoute:
    ProtectedEmprestimosEmprestimoAdministrativoIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
